### ISSUE TITLE
Choose a project

### ISSUE THREAD

**Issue by MrNo-Body** [MrNo-Body/ecam-app-android#1]
We must choose an app that fit the requirements. See paper on Claco.

**Comment by MrNo-Body** [comment]
Résumé des idées lors du premier brainstorming : 
1. Radio internet ([transistor](https://f-droid.org/repository/browse/?fdfilter=transistor&fdid=org.y20k.transistor))
1. App qui reproduit un site internet
1. Indiquer la composition des aliments ([openfoodfacts](http://openfoodfacts.org) - [appli](https://f-droid.org/repository/browse/?fdfilter=openfood&fdid=openfoodfacts.github.scrachx.openfood))
1. Wikipédia offline ([Kiwikx](https://f-droid.org/repository/browse/?fdfilter=kiwix&fdid=org.kiwix.kiwixmobile))
1. Application pour diabétique, glycémie, insuline,...
1. Rechercher les paroles d'une musique et les afficher ([QuickLyric](https://f-droid.org/repository/browse/?fdfilter=quicklyr&fdid=com.geecko.QuickLyric))
1. Regrouper les restos sur Alma et les présenter
1. News à partir d'un flux RSS
1. Jeux de rôle

**Comment by IsmaelAka** [comment]
# Application Android

Réunion du 24/03/2017.
Présent: Tous

Application pour OpenFoodFacts.org

## Diagramme de classe 

- Même diagramme que le projet Weather :
    - class Query (récup donnée internet)
    - Class découpe Json (base de donnée local)
    - Class recycleur view
    - Class view adapter avec rotation
- activité qui permet d'entrée le code barre, cette vue renvoi vers une activité donne le details de l'aliment.
- Une seconde activité qui liste les produits favoris (et/ou les plus consulté)
- Une activité avec préférence/option

## Croquis des vue
- la recherche d'aliment ou page avec favoris
- la vue suivante est le résultat de la recherche ou bien le résulat de quand on a cliqué sur l'aliment favoris
- activité qui fait le détail d'un produit 
    - au moins 3 vues différentes ou 4 (selon le résultats de la recherche) : 
        - Vue avec recherche
        - vue avec résultat de la recherche (scrollable)
        - Vue avec liste favoris (scrollable)
        - Vue avec l'aliment 

## Préférences
- changer la taille des caractères.
- modifier le fond (couleur,etc).
- mettre certain allergènes en couleur (rouge).
- afficher photo de l'aliment ou non.
- Bouton telecharger base de donnée.
- mode nuit pour pas tuer les yeux.
	
## Pour mardi:
- Diagramme de class
- Croquis

## TODO List
- plusieur acti = check
- preference (options) = check
- recycleur view = check
- base de donnée local = check
- recup des donnée d'internet = check
- rotation d'ecran
