### ISSUE TITLE
Class: FoodPreferenceActivity

### ISSUE THREAD

**Issue by IsmaelAka** [MrNo-Body/ecam-app-android#15]

**Comment by Neilack** [comment]
![preference](https://cloud.githubusercontent.com/assets/11157364/25120395/27b56038-241e-11e7-8878-72e5b5567ae5.PNG)
# Préférences

- changer la taille des caractères.
- modifier le fond (couleur,etc).
- mettre certain allergènes en couleur (rouge).
- afficher photo de l'aliment ou non.
- Bouton telecharger base de donnée.
- mode nuit pour pas tuer les yeux.

**Comment by MrNo-Body** [comment]
Voilà la partie de code pour le intent : 
```
    @Override
    public void onClick(int index) {
        Context context = this;
        Class destinationClass = WeatherForecastDetails.class;
        Intent intent = new Intent(context, destinationClass);
        intent.putExtra(Intent.EXTRA_INDEX, index);
        startActivity(intent);
    }
```
