### ISSUE TITLE
Diagramme de classe

### ISSUE THREAD

**Issue by MrNo-Body** [MrNo-Body/ecam-app-android#2]
En fonction du projet choisi, déterminer son diagramme des classes afin de distribuer les tâches.

**Comment by remytms** [comment]
Voir rapport de la réunion du 24 mars: https://github.com/MrNo-Body/ecam-app-android/issues/1#issuecomment-289037461

**Comment by MrNo-Body** [comment]
Voilà le premier jet du diagramme.
[Diagramme des classes](https://drive.google.com/open?id=0B44nYyviL39cU1FGUDRKcmJPY3M)

![diaclassefood](https://cloud.githubusercontent.com/assets/17589077/24353712/25c3fd10-12ef-11e7-94f1-c6c2d37019c2.png)
