### ISSUE TITLE
Design of application

### ISSUE THREAD

**Issue by remytms** [MrNo-Body/ecam-app-android#3]
Faire des croquis pour les activités de notre application. Voir rapport de réunion : https://github.com/MrNo-Body/ecam-app-android/issues/1#issuecomment-289037461

**Comment by remytms** [comment]
Voici les croquis de l'application.

![croquis](https://cloud.githubusercontent.com/assets/17589077/24353491/151eee8a-12ee-11e7-8c80-081145c2005e.jpg)

Dessiné ensemble lors de la réunion du 27 mars midi.

**Comment by IsmaelAka** [comment]
- screenRotate  ==> Réaliser un autre dossier de fichier XML pour la vue en paysage et non une "class" screenRotate. Normalement androïde le fait lui même. Juste spécifier les fichiers XML dans les bon nom de répertoire.

- recycler view : Seul la vue "liste de favoris" et "résultat recherche" on besoin du recyler mais il faut voir s'il est possible de faire un seul recycler pour 2 layouts

- Les photo des aliment sont à télécharger depuis le lien donné par l'api (on réalisera l'application sans photo dans un premier temps, juste garder la possibilité de le réaliser pour l'instant)
