### ISSUE TITLE
Show "go back" arrow in the menu

### ISSUE THREAD

**Issue by remytms** [MrNo-Body/ecam-app-android#33]
Afficher une flèche "retour en arrière" dans le menu en haut de la fenêtre.

**Comment by Neilack** [comment]
Il est vraiment nécessaire de le faire ?
C'est pas redondant avec le bouton retour du téléphone ?

**Comment by remytms** [comment]
Ça fait pas tout à fait la même chose que le bouton du téléphone car le bouton du téléphone sert à revenir à l'activité précédente. Tandis qu'avec le bouton back tu retournes à une activité bien précise. Mais je suis d'accord que ce n'est pas une priorité. Donc laissons de coté pour l'instant.
