### ISSUE TITLE
Make preferences persistant

### ISSUE THREAD

**Issue by remytms** [MrNo-Body/ecam-app-android#36]
Faire en sorte que les préférences soit enregistrée. Pour l'instant lorsqu'on coche une case, elle n'est plus cochée si on quite l'application et qu'on revient dessus.

**Comment by remytms** [comment]
Qui s'en charge ?

**Comment by MrNo-Body** [comment]
Je vais le faire, on avait fait ça en labo ça devrait aller

**Comment by MrNo-Body** [comment]
Je résume ce que je dois faire ici, histoire d'être sur de ne pas faire de la merde.

Pour les préférences on va sauver les paramètres sous forme de clé/valeurs, ce sera enregistré dans un fichier sur le téléphone.

Pour faire ça : 
 - J'ajoute des clés dans le fichier preference.xml pour les paramètre que l'on veut enregistrer.
ex : android:key="nightmode", pour la checkboxNight.

- Dans le fichier preference activity, dans le oncreate : 
addPreferencesFromResource (R.xml.preference);

- Dans le main activity, il faut que je dise d'aller chercher les valeurs enregistrées au moment du oncreate, mais la je ne vois pas trop.

- Ne pas oublier d'ajouter la dépendance dans le gradle : compile ’com.android.support:preference-v7:25.0.0’

**Comment by Neilack** [comment]
Si tu peux juste me creer un fichier dans lequel sauvegarder l'état de mes boutons choix c'est nickel, fait le juste sur la checkbox, et je m'occupe du reste

**Comment by remytms** [comment]
Ça m'a l'air bon. :)

**Comment by MrNo-Body** [comment]
J'ai actuellement un petit problème car les techniques pour enregistrer les préférences que j'ai vue proposent de créer un fichier xml preference, mais ce n'est pas un Relativelayout comme dans notre cas mais un PreferenceScreen dans le dossier ressource/xml, et ça permet d'enregistrer automatique des "key". Donc je ne vois pas trop quoi faire... Je cherche encore.

**Comment by Neilack** [comment]
t'a regardé là:
https://developer.android.com/training/basics/data-storage/shared-preferences.html 
?

**Comment by MrNo-Body** [comment]
Oui, c'est d’ailleurs de la que viens en partie le cours du prof

**Comment by remytms** [comment]
@MrNo-Body , je te propose, sur une nouvelle branche, de créer une nouvelle page de préférence qui utilise la technique "PreferenceScreen". Quitte à devoir retirer les boutons et options qui existent déjà.

Si ça marche mieux on transférera petit à petit les options que @Neilack a codée vers ta branche.

**Comment by MrNo-Body** [comment]
J'ai trouvé le moyen de le faire en gardant le layout actuel, mais ça ne fonctionne pas, si quelqu'un veut checker la branche FixPref. 

Voici deux sources :
[Premier lien](https://www.tutorialspoint.com/android/android_shared_preferences.htm)
[Deuxième lien](http://stackoverflow.com/questions/25261296/how-to-save-a-checkbox-state-in-android-app)

**Comment by Neilack** [comment]
Le problème est dans la récuperation des données je crois, quand je fais : 
if(PreferenceManager.getDefaultSharedPreferences(this).edit()
                    .putBoolean("checkBoxNight", nightmode).commit())
            {
                Toast.makeText(this, "saved", Toast.LENGTH_SHORT).show();
            }
commit renvoi True si ça a bien été sauvergardé, du coup je pense que ça viens du debut du code, je continue de regarder

Edit:
Effectivement quand tu met "nightmode" et "photo" dans if, ils sont jamais set à true

**Comment by Neilack** [comment]
Tu met jamais tes valeurs à true ou a false.
Je vais te tuer mec, je vais t'arracher tes poils un à un et te les faire bouffer

**Comment by Neilack** [comment]
Je merge pas, je vais mettre ça manuellement dans la nouvelle version

**Comment by remytms** [comment]
@Neilack , tu as fermé cette issue. Tu sais indiquer les Pull Request qui ont réglé le problème ici en commentaire. Ou alors réouvrir l'issue. :)

**Comment by Neilack** [comment]
la #36 dans Fixpref, mais je l'ai implementé dans ma branche, je vais bientot merge le tout, je corrige des bug

**Comment by Neilack** [comment]
je close
