### ISSUE TITLE
SQL database

### ISSUE THREAD

**Issue by Neilack** [MrNo-Body/ecam-app-android#39]
Dans l’énoncé il est indiqué que les données doivent être enregistrer dans une base SQL et non un simple Json

**Comment by remytms** [comment]
@Neilack Ok, et tu veux que je m'en charge cette aprèm ?

**Comment by remytms** [comment]
Je me mets à bosser là dessus. :)

**Comment by Neilack** [comment]
déso j'étais en cours j'ai pas vu :/
ok dac, je peux le faire aussi si t'es occupé y'a pas de souci

**Comment by remytms** [comment]
Pas de soucis, je m'en doutais. :) Comme tu vois j'ai pu régler le problème. :)

**Comment by Neilack** [comment]
Bon ben déso, j'avais oublié de m'assigné aux issue que j'avais mis et que j'allais faire, je pensais juste listé ce que je faisais ici pour que tout le monde voient. My bad, learned

**Comment by remytms** [comment]
Pas de soucis, j'avais du temps. Et comme ça c'est fait. Mais il reste d'autres trucs à faire. ;)
