### ISSUE TITLE
Favorite not removed when clicking on favorite button

### ISSUE THREAD

**Issue by remytms** [MrNo-Body/ecam-app-android#41]
Quand on clique sur le bouton pour retirer un favori de la liste des favoris. Il est bien supprimé de la base de donnée, mais reste afficher dans la liste des favoris.

En gros l'affichage de la liste des favoris ne se met pas à jour au bon moment.

Si quelqu'un à une solution, … Mais c'est pas une priorité.

**Comment by Aladdin77** [comment]
Le bug est réparé, il fallait juste déplacer les lignes de codes accède à la BD dans la class FoodMainActivity
