### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by IsmaelAka** [MrNo-Body/ecam-app-android#43]
JE vais tenter de rendre l'application plus agréable en terme de design

**Comment by remytms** [comment]
Super !

**Comment by IsmaelAka** [comment]
@remytms @yunide @MrNo-Body @Neilack  
Vous savez tous ouvrir l'application sur votre tel ou sur émulateur? Moi des que je test sur un teléphone la dernière version l'app crash des le début.. 
Je vais modifier continuer a modifier le design sans pouvoir voir a quoi cela ressemble dans l'app..

**Comment by remytms** [comment]
@IsmaelAka , j'arrive à la lancer. Est-ce que tu as toujours le problème ?

Sinon, est-ce qu'on peut considérer ce bug comme résolu par ta pull request #56 ?

**Comment by remytms** [comment]
@IsmaelAka , je te laisse fermer cet issue quand tu juges que tu l'a résolue. ;)

**Comment by IsmaelAka** [comment]
@remytms je suis encore entrain de modifier le design donc je la laisse ouverte pour le moment :p
