### ISSUE TITLE
Write the report

### ISSUE THREAD

**Issue by remytms** [MrNo-Body/ecam-app-android#44]
On le fait en LaTeX ? Comme ça on peut mettre les fichier latex sur git aussi, ce qui permet de travailler à plusieurs.

On en discute ici. :)

**Comment by MrNo-Body** [comment]
OK, c'est à rendre le même jours que la présentation ou bien mardi c'est juste la présentation?

**Comment by IsmaelAka** [comment]
oui @MrNo-Body  tt est a remettre pour ce jour on doit poster dans notre repository github un rapport pour cette date

**Comment by IsmaelAka** [comment]
@remytms le soucis c'est que Abdel Yassine et moi on sait pas utiliser ce logiciel (et niveau temps c'est short pour apprendre a le faire) donc je sais comment on va s'arranger

**Comment by remytms** [comment]
@IsmaelAka , oui, je comprends. C'est un pour ça que je posais la question. Y a pas de problème pour utiliser un autre logiciel. :)

**Comment by Neilack** [comment]
le rapport il dois être super élaborer ou c'est juste la description du code avec des commentaires dans le code ?

**Comment by MrNo-Body** [comment]
Il me semble que l'on doit expliquer un minimum les fonctionnalités de notre application, et la manière dont on a décidé d'implémenté le code. Pas juste le code copié/collé le code.

**Comment by remytms** [comment]
Pour le rapport il faut se mettre dans la tête de quelqu'un qui devrait se plonger dans le code mais qui ne sait pas ce qu'on a fait.

Donc une présentation de l'application et de ses fonctionnalité. Puis expliquer un peu ce que fait chaque classe et ou trouver les éléments pour modifier le programme.

L'idée c'est que quelqu'un qui lise ce rapport puisse après modifier application pour ses propre besoin.

**Comment by MrNo-Body** [comment]
Pour le rapport, je propose plusieurs points : 
- Expliquer le but de l'application
- Présenter les activity, 1 point par activity ? (5 activity)
- Expliquer les améliorations éventuelles

D'autres idées ?

@MrNo-Body  je ne vois quoi d'autre mettre je pense que c'est bien comme ça moi perso

**Comment by MrNo-Body** [comment]
Voilà un début du rapport, dites moi s'il faut ajouter/changer/supprimer des choses. Je suis ouvert à toutes propositions, dans le cadre de ce cours bien sûr :p
[PrésentationsAppEcam.docx](https://github.com/MrNo-Body/ecam-app-android/files/968093/PresentationsAppEcam.docx)

C'est un docx, je ne savais pas quoi faire :p

**Comment by IsmaelAka** [comment]
[PresentationsAppEcam.docx](https://github.com/MrNo-Body/ecam-app-android/files/968314/PresentationsAppEcam.docx)

Ceux qui ont bossé sur les activités vous préférez compléter vous même ? ou bien me poster ici en comm vos explications ?

**Comment by MrNo-Body** [comment]
Quelque idée d'amélioration (y compris celle proposée dans l'autre issue #54 : 
- Trier alphabétiquement la liste des favoris
- menu déroulant pour aller sur la page qu'on veut directement
- Permettre d'ajouter des produits
- Ajouter d'autres détails pour les produits

**Comment by MrNo-Body** [comment]
New version, nouveau contenu temporaire, encore a modifié, les idées principales sont la.

[PrésentationsAppEcam.docx](https://github.com/MrNo-Body/ecam-app-android/files/968888/PresentationsAppEcam.docx)

**Comment by remytms** [comment]
Mes propositions pour le rapport  :

# FoodDetailsActivity

Cette activité affiche le détail d'un produit. Comme son nom, les catégories dans lesquels il est rangé. Il est possible d'obtenir plein d'informations concernant un produit. Toutes les informations ne sont pas disponibles dans l'application pour l'instant mais tout est en place pour facilement aller rechercher ces informations sur le serveur de donnée.
C'est dans cette activité que l'on peut choisir de marqué un produit comme favori ou de le retirer
L'interface est une ScrollView qui permet d'afficher toutes les informations, elle se trouve dans le fichier `activity_food_details.xml`.
On arrive dans cette activité à partir de l'activité FoodSearchActivity ou FoodFavoriteActivity.

# FoodFavoriteActivity
Cette activité présente la liste des produits marqués comme favori par l'utilisateur. Elle est similaire à l'activité FoodSearchActivity. Elle utilise un RecycleView comme FoodSearchActivity et le même layout pour afficher les élements de la liste.
La différence avec FoodSearchActivity est que FoodSearch affiche une liste après avoir fait une recherche sur l'API en ligne. Tandis que FoodFavoriteActivity va chercher les produits qui sont enregistrés dans la base de donnée locale.

**Comment by MrNo-Body** [comment]
[PresentationsAppEcam.docx](https://github.com/MrNo-Body/ecam-app-android/files/970013/PresentationsAppEcam.docx)

Final version V1.0

**Comment by MrNo-Body** [comment]
Final Version V1.1
[PresentationsAppEcam.docx](https://github.com/MrNo-Body/ecam-app-android/files/970054/PresentationsAppEcam.docx)

**Comment by Aladdin77** [comment]
On le post en pdf sur github?
