### ISSUE TITLE
For the main search, say when not connected to internet or not finding result

### ISSUE THREAD

**Issue by Aladdin77** [MrNo-Body/ecam-app-android#48]

**Comment by remytms** [comment]
Quelqu'un à le temps de s'en occuper ? Si oui, il peut s'assigner à cette issue. :)

Sinon, on l'indiquera comme amélioration dans le rapport. :)

**Comment by Aladdin77** [comment]
Je vais voir si j'ai le temps, avant je préfère essayer de faire la flèche retour arrière. :) sauf si quelqu'un la finit avant moi.

**Comment by Aladdin77** [comment]
on mettra dans améliorations
