### ISSUE TITLE
Change textStyle

### ISSUE THREAD

**Issue by Neilack** [MrNo-Body/ecam-app-android#51]

**Comment by Neilack** [comment]
J'arrive à changer la taille des textview via le style, mais le souci c'est que quand on change la taille, on perd le theme appliqué precedement. Du coup ce que je dois faire ça serait réalisé toute les combinaisons possible de taille de texte (petit, normal, grand) et les themes  de couleur.....
une idée ?

**Comment by Aladdin77** [comment]
On mettra dans améliorations:)
