### ISSUE TITLE
Improve Go back arrow

### ISSUE THREAD

**Issue by Aladdin77** [MrNo-Body/ecam-app-android#53]
Pour que quand on appuie sur la flèche de retour arrière depuis la page détails (vers favoris quand c'est le cas) on rafraîchisse la liste de favoris. 
exemple: 
Page favoris: click sur aliment "chips" -> on est sur détails "chips", on décoche l'étoile pour enlever des favoris-> on click sur la flèche de retour arrière => chips est plus dans la liste.
C'est pas le cas pour l'instant :'(

**Comment by Neilack** [comment]
https://www.youtube.com/watch?list=RDh61QG4s0I3U&v=mMfxI3r_LyA
done ;) ;) ;) <3 <3 <3
