### ISSUE TITLE
Idea of enhancement

### ISSUE THREAD

**Issue by Aladdin77** [MrNo-Body/ecam-app-android#54]
-Trier alphabétiquement la liste des favoris
-menu déroulant pour aller sur la page qu'on veut directement
-Afficher image aliment (fait)
-utiliser une "searchview" plutot qu'une edit box pour la recherche ( fait )
-Meilleure transition entre vue

**Comment by IsmaelAka** [comment]
@Aladdin77 pour les transition j'ai essayer le truc c'est qu'il faut set l'API minimum a 19 et pas a 15 comme ce que j'on a nous en ce moment

**Comment by Aladdin77** [comment]
Dis moi où il faut changer comme ça je test sur mon téléphone :)
