### ISSUE TITLE
Check List de l'énoncé

### ISSUE THREAD

**Issue by Neilack** [MrNo-Body/ecam-app-android#59]
[ECAM-AM4L-2017-Projet.pdf](https://github.com/MrNo-Body/ecam-app-android/files/967049/ECAM-AM4L-2017-Projet.pdf)

**Comment by Neilack** [comment]
- Plusieurs activités 👍 
- Des préférences 👍 
- Une recycler view (dans FoodSearchActivity) 👍 
- Une base de donnée locale 👍 
- récupérer des données d'internet 👍 
- fonctionner en portrait et paysage👍  

TODO: En priorité
- recycler view
- fonctionnement portrait/paysage #58

**Comment by Aladdin77** [comment]
Le recyclerview est utilisé dans la recherche non? @remytms 
edit: @remytms si tu as le temps tu saurais utiliser la recycler view pour la page de détails , quand y'a trop d'ingrédient on peut pas voir le bouton favoris. Et en mode paysage ça arrive vite.:)

**Comment by IsmaelAka** [comment]
@Neilack Chez moi ça fonctionne en paysage l'application

**Comment by Aladdin77** [comment]
Oui mais la disposition est mauvaise parfois, j'ai modifier pour que la main page soit bien positionné quand l'écran est en paysage. (tout bête) je vais merge :)

**Comment by remytms** [comment]
Oui le RecycleView est utiliser dans FoodSearchActivity et FoodFavoriteActivity.

Pour ce qui est de la page FoodDetailsActivity, je ne pense pas qu'un RecycleView fera l'affaire car ce n'est pas plusieurs fois la même chose qui est afficher. Je vais chercher un peu.

**Comment by Aladdin77** [comment]
Non c'est bon j'ai résolu le souci :)
