### ISSUE TITLE
How to use Github

### ISSUE THREAD

**Issue by MrNo-Body** [MrNo-Body/ecam-app-android#6]
Résumé des commandes à utiliser dans Gitbash pour travailler sur le projet.
[Ici le lien](http://rogerdudler.github.io/git-guide/)

N'hésitez pas à ajouter en commentaire des solutions à des problèmes que vous avez déjà eu, histoire de ne pas faire deux fois la même erreur.

_Un erreur ça arrive, c'est humain. Refaire une deuxième fois la même erreur ça devient de la négligence._

**Comment by IsmaelAka** [comment]
# Commandes de base faites en classe avec Rémy
[Explications Git de base.pdf](https://github.com/MrNo-Body/ecam-app-android/files/875003/Explications.Git.de.base.pdf)

**Comment by remytms** [comment]
# Configurer votre nom sur git
Pour que vos commit soit correctement référencé sur github, il faut configurer votre git local. Simplement lancer ces commandes :
```
$ git config --global user.name "Mon Nom Bien Propre Ou Mon Pseudo"
$ git config --global user.email "mon_eamil_que_jai_mis_a_linscription_sur_github@example.com"
```

**Comment by remytms** [comment]
# Pour aller plus vite avec git

Il peut être intéressant d'avoir des raccourcis pour aller plus vite. Par exemple taper `git st` à la place de `git status` ou encore `git co` à la place de `git checkout`.

```
$ git config --global alias.co checkout
$ git config --global alias.br branch
$ git config --global alias.ci commit
$ git config --global alias.st status
```
