### ISSUE TITLE
Rapport & Slides

### ISSUE THREAD

**Issue by IsmaelAka** [MrNo-Body/ecam-app-android#63]
Les gars ont fait comment pour le rapport et les slides ? on fait un doc online sur le drive et on modifie ensemble ou bien on fait en sorte qu'une personne se charge du rapport et une autre des slides  ? 

Et aussi départager qui va dire quoi pendant la présentation (mine de rien on passe demain mdr =p)

**Comment by Aladdin77** [comment]
Pour la présentation je veux bien la présenter en gros grace à mobizen ( en gros sur le pc on voit en temps réel l'ecran de mon téléphone). Faudrait des slides par activity aussi. Le rapport on devrait faire un brainstorming ensemble :)

**Comment by IsmaelAka** [comment]
@Aladdin77  c'est pour demain le rapport non ?

**Comment by Aladdin77** [comment]
oui:p chris a envoyé un début de rapport par mail

**Comment by MrNo-Body** [comment]
A mon avis faut pas trop se casser la tête pour la présentation, faut juste que les autres voient ce qu'on a fait.

**Comment by Aladdin77** [comment]
Faut leur en mettre plein la vue, j'ai préparé les feux d'artifices

@Aladdin77 Il y a des ballons gonflables dans l'armoire eurobot si tu veux ;-)

**Comment by IsmaelAka** [comment]
je vais taffer sur le rapport maintenant si vous avez des explications a donner sur les vues postez les ici je suis preneur je peut et je vais m'occuper de la rédaction ensuite je vous enverrais le doc et on corrige ensemble.

@IsmaelAka J'ai déjà commencé un rapport dans l'autre issue, check le ;-)
